/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "category",
      label: "通知",
      items: [
        "open-api/notice/TLS",
        "open-api/notice/update-log"
      ],
    },
    {
      type: "category",
      label: "开始使用",
      items: [
        "open-api/getting-started/getting-started",
        "open-api/getting-started/postman-use",
        "open-api/getting-started/origin",
        "open-api/getting-started/auth",
        "open-api/getting-started/refresh-auth",
        "open-api/getting-started/temp-auth",
        "open-api/getting-started/question-answer"
      ],
    },
    {
      type: "category",
      label: "企业通讯录",
      items: [
        "open-api/corporation/info",
        "open-api/corporation/corporation-info",
        "open-api/corporation/get-departments",
        "open-api/corporation/get-all-staffs",
        "open-api/corporation/get-staff-ids",
        "open-api/corporation/get-staff-backLog",
        "open-api/corporation/get-roles-group",
        "open-api/corporation/get-roles",
        "open-api/corporation/update-roles",
        "open-api/corporation/question-answer"
      ],
    },






  ],
};

module.exports = sidebars;
